analyte_list = "" # path single column list of PTM sites to build models for
modifier_list = "" # path single column list of PTM modifiers to include features of
keep_features = [""] # List of features to keep regardless of filter criteria (See documentation for feature naming conventions)
remove_features = [""] # List of features to remove regardless of filter criteria (See documentation for feature naming conventions)
only_use_listed_data = false # use only listed data files. If false, will use all TSV (*.tsv) files in the data/ folder
site_separator = "|" # Character used to separate the gene from the site (ex: ABC1|K234)
filter_by_ppi = true # filter the modifier lists by removing proteins not known to have PPI with the host protein of interest
do_feature_selection = false # whether to perform feature selection (independent of ppi filtering)

[params]
max_na_ratio = 0.1 # Max ratio of missing values allowed in a feature

[[data]] # optional list of [[data]] if you need to specify
path = "host/example.tsv" # Path to data file (path relative to data folder)
ignore_cols = [""] # List of columns to ignore in file (e.g. multiple ID columns)
# name = "Custom Name" # Optional name for dataset. If not set, defaults to path without file extension (example)